<?php

use Illuminate\Database\Seeder;

class SalesOrderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$SalesOrder = array(
            array(
                'trans_type'=>201,
                'invoice_type'=>'directOrder',
                'debtor_no'=>1,
                'branch_id'=>1,
                'person_id'=>1,
                'reference'=>'SO-0001',
                'order_reference_id'=>0,
                'order_reference'=>NULL,
                'ord_date'=>date("Y-m-d"),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>92000,
                'paid_amount'=>0,
                'payment_term'=>2,
                'created_at'=>date('Y-m-d H:i:s')
            ),
            array(
                'trans_type'=>201,
                'invoice_type'=>'directOrder',
                'debtor_no'=>2,
                'branch_id'=>2,
                'person_id'=>1,
                'reference'=>'SO-0002',
                'order_reference_id'=>0,
                'order_reference'=>NULL,
                'ord_date'=>date("Y-m-d", strtotime("-12 days")),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>80500,
                'paid_amount'=>0,
                'payment_term'=>2,
                'created_at'=>date('Y-m-d H:i:s', strtotime("-12 days"))
            ),
            array(
                'trans_type'=>201,
                'invoice_type'=>'indirectOrder',
                'debtor_no'=>4,
                'branch_id'=>4,
                'person_id'=>1,
                'reference'=>'SO-0003',
                'order_reference_id'=>0,
                'order_reference'=>NULL,
                'ord_date'=>date("Y-m-d", strtotime("-17 days")),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>3910,
                'paid_amount'=>0,
                'payment_term'=>0,
                'created_at'=>date('Y-m-d H:i:s', strtotime("-17 days"))
            ),
            array(
                'trans_type'=>202,
                'invoice_type'=>'directInvoice',
                'debtor_no'=>4,
                'branch_id'=>4,
                'person_id'=>1,
                'reference'=>'INV-0001',
                'order_reference_id'=>3,
                'order_reference'=>'SO-0003',
                'ord_date'=>date("Y-m-d", strtotime("-17 days")),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>3910,
                'paid_amount'=>0,
                'payment_term'=>2,
                'created_at'=>date('Y-m-d H:i:s', strtotime("-17 days"))
            ),
            array(
                'trans_type'=>201,
                'invoice_type'=>'indirectOrder',
                'debtor_no'=>2,
                'branch_id'=>2,
                'person_id'=>1,
                'reference'=>'SO-0004',
                'order_reference_id'=>0,
                'order_reference'=>NULL,
                'ord_date'=>date("Y-m-d", strtotime("-12 days")),
                'from_stk_loc'=>'JA',
                'payment_id'=>1,
                'total'=>11615,
                'paid_amount'=>0,
                'payment_term'=>0,
                'created_at'=>date('Y-m-d H:i:s', strtotime("-12 days"))
            ),
            array(
                'trans_type'=>202,
                'invoice_type'=>'directInvoice',
                'debtor_no'=>2,
                'branch_id'=>2,
                'person_id'=>1,
                'reference'=>'INV-0002',
                'order_reference_id'=>5,
                'order_reference'=>'SO-0004',
                'ord_date'=>date("Y-m-d", strtotime("-12 days")),
                'from_stk_loc'=>'JA',
                'payment_id'=>1,
                'total'=>11615,
                'paid_amount'=>615,
                'payment_term'=>1,
                'created_at'=>date('Y-m-d H:i:s', strtotime("-12 days"))
            ), 
            array(
                'trans_type'=>202,
                'invoice_type'=>'indirectInvoice',
                'debtor_no'=>1,
                'branch_id'=>1,
                'person_id'=>1,
                'reference'=>'INV-0003',
                'order_reference_id'=>1,
                'order_reference'=>'SO-0001',
                'ord_date'=>date("Y-m-d"),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>920000,
                'paid_amount'=>500,
                'payment_term'=>2,
                'created_at'=>date('Y-m-d H:i:s')
            ),
            array(
                'trans_type'=>201,
                'invoice_type'=>'indirectOrder',
                'debtor_no'=>4,
                'branch_id'=>4,
                'person_id'=>1,
                'reference'=>'SO-0005',
                'order_reference_id'=>0,
                'order_reference'=>NULL,
                'ord_date'=>date("Y-m-d"),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>10350,
                'paid_amount'=>0,
                'payment_term'=>0,
                'created_at'=>date('Y-m-d H:i:s')
            ),
            array(
                'trans_type'=>202,
                'invoice_type'=>'directInvoice',
                'debtor_no'=>4,
                'branch_id'=>4,
                'person_id'=>1,
                'reference'=>'INV-0004',
                'order_reference_id'=>8,
                'order_reference'=>'SO-0005',
                'ord_date'=>date("Y-m-d"),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>10350,
                'paid_amount'=>0,
                'payment_term'=>1,
                'created_at'=>date('Y-m-d H:i:s')
            ),
            array(
                'trans_type'=>201,
                'invoice_type'=>'indirectOrder',
                'debtor_no'=>3,
                'branch_id'=>3,
                'person_id'=>1,
                'reference'=>'SO-0006',
                'order_reference_id'=>0,
                'order_reference'=>NULL,
                'ord_date'=>date("Y-m-d", strtotime("-21 days")),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>9200,
                'paid_amount'=>0,
                'payment_term'=>0,
                'created_at'=>date('Y-m-d H:i:s',strtotime("-21 days"))
            ),
            array(
                'trans_type'=>202,
                'invoice_type'=>'directInvoice',
                'debtor_no'=>3,
                'branch_id'=>3,
                'person_id'=>1,
                'reference'=>'INV-0005',
                'order_reference_id'=>10,
                'order_reference'=>'SO-0006',
                'ord_date'=>date("Y-m-d"),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>195500,
                'paid_amount'=>0,
                'payment_term'=>1,
                'created_at'=>date('Y-m-d H:i:s')
            ),
            array(
                'trans_type'=>201,
                'invoice_type'=>'indirectOrder',
                'debtor_no'=>2,
                'branch_id'=>2,
                'person_id'=>1,
                'reference'=>'SO-0007',
                'order_reference_id'=>0,
                'order_reference'=>NULL,
                'ord_date'=>date("Y-m-d",strtotime("-20 days")),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>2875000,
                'paid_amount'=>0,
                'payment_term'=>0,
                'created_at'=>date('Y-m-d H:i:s')
            ),
            array(
                'trans_type'=>202,
                'invoice_type'=>'directInvoice',
                'debtor_no'=>2,
                'branch_id'=>2,
                'person_id'=>1,
                'reference'=>'INV-0006',
                'order_reference_id'=>12,
                'order_reference'=>'SO-0007',
                'ord_date'=>date("Y-m-d",strtotime("-20 days")),
                'from_stk_loc'=>'PL',
                'payment_id'=>1,
                'total'=>2875000,
                'paid_amount'=>0,
                'payment_term'=>0,
                'created_at'=>date('Y-m-d H:i:s')
            ),
        );

        DB::table('sales_orders')->truncate();
		DB::table('sales_orders')->insert($SalesOrder);
    }
}